### PR TITLE
Issue91: Fix analytics log error

### LINKED ISSUE #91: analytics log error
m.analyticsURL is not valid here:

https://github.com/apigee/istio-mixer-adapter/blob/master/adapter/analytics/analytics.go#L513

The logging line should be fixed and the var should be removed.

### PR DESCRIPTION
**Pull request by vilobhmm**
Fix analytics log error.

closes #91

### CODE REVIEW

**Comment by theganyo** [comment]
Two things:
1. The unused variable m.analyticsURL is still in the struct. We need to remove it.
2. Instead of just removing the URL from the logging, I'd rather we'd put in the real URL.

File: adapter/analytics/analytics.go [hunk 1]
```diff
@@ -510,7 +509,7 @@ func (m *manager) signedURL(subdir, filename string) (string, error) {
 	defer resp.Body.Close()
 
 	if resp.StatusCode != http.StatusOK {
-		return "", fmt.Errorf("status (code %d) returned from %s: %s", resp.StatusCode, m.analyticsURL, resp.Status)
+		return "", fmt.Errorf("status (code %d) returned from %s: %s", resp.StatusCode, u.Path, resp.Status)
```
Comment (theganyo) [inline adapter/analytics/analytics.go]: Can we use this u.String() instead of u.Path, so we have the whole thing? Thanks.
